# Generated by Django 5.0.14 on 2026-02-09 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('transcription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('realtime_incremental', 'Real-time Incremental'), ('post_meeting', 'Post-meeting')], max_length=30)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_token_count', models.IntegerField(blank=True, null=True)),
                ('output_token_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='started', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('segment_count', models.IntegerField(blank=True, null=True)),
                ('suggestion_count', models.IntegerField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_runs', to='meetings.meeting')),
            ],
            options={
                'db_table': 'copilot_runs',
            },
        ),
        migrations.CreateModel(
            name='CopilotFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unresolved_items_json', models.JSONField(blank=True, default=list)),
                ('changes_since_last_meeting', models.TextField(blank=True)),
                ('suggested_next_agenda', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_follow_up', to='meetings.meeting')),
                ('previous_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_follow_up', to='meetings.meeting')),
                ('copilot_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_copilot.copilotrun')),
            ],
            options={
                'db_table': 'copilot_follow_up',
            },
        ),
        migrations.CreateModel(
            name='CopilotSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('action_item', 'Action Item'), ('decision', 'Decision'), ('risk', 'Risk'), ('question', 'Open Question')], max_length=20)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='proposed', max_length=20)),
                ('dedupe_key', models.CharField(db_index=True, max_length=255)),
                ('source_segment_ids', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(choices=[('ai', 'AI'), ('user', 'User')], default='ai', max_length=10)),
                ('accepted_action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestion', to='transcription.actionitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_suggestions', to='meetings.meeting')),
            ],
            options={
                'db_table': 'copilot_suggestions',
            },
        ),
        migrations.CreateModel(
            name='SpeakerUserMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_speaker_maps', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_user_maps', to='meetings.meeting')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_maps', to='meetings.speaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'speaker_user_map',
            },
        ),
        migrations.CreateModel(
            name='CopilotNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('action_due', 'Action Item Due'), ('action_overdue', 'Action Item Overdue'), ('weekly_digest', 'Weekly Digest'), ('meeting_reminder', 'Meeting Reminder')], max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transcription.actionitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_notifications', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'copilot_notifications',
                'indexes': [models.Index(fields=['user', 'scheduled_at', 'status'], name='copilot_not_user_id_f957f6_idx'), models.Index(fields=['meeting', 'type', 'status'], name='copilot_not_meeting_7fefb1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='copilotrun',
            index=models.Index(fields=['meeting', 'started_at'], name='copilot_run_meeting_e5846a_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotrun',
            index=models.Index(fields=['status', 'started_at'], name='copilot_run_status_4fe9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotsuggestion',
            index=models.Index(fields=['meeting', 'type', 'status'], name='copilot_sug_meeting_4c369a_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotsuggestion',
            index=models.Index(fields=['meeting', 'dedupe_key'], name='copilot_sug_meeting_246588_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotsuggestion',
            index=models.Index(fields=['created_at'], name='copilot_sug_created_f1068a_idx'),
        ),
        migrations.AddIndex(
            model_name='speakerusermap',
            index=models.Index(fields=['meeting', 'user'], name='speaker_use_meeting_a5e5e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='speakerusermap',
            unique_together={('meeting', 'speaker')},
        ),
    ]
